openapi: 3.0.0

servers:
  - description: Local test server
    url: http://127.0.0.1:3000
  - description: AWS EC2
    url: http://52.78.27.117:3000

info:
  version: '1.0.0'
  title: 'U-link'
  description: 'University-link'
  contact:
    email: deadlock@kakao.com

tags:
  - name: User
    description: Access User data
  - name: Schedule
    description: Access Schedule data
  - name : Chatting
    description: Access Chatting data
  - name : Notice
    description: Access Notice data
  - name : Social
    description: Access Social data
  - name : Cart
    description: Access Cart data
  - name : Subject
    description: Access Subject data

paths:
  /user/signup:
    $ref: './docs/user/signUp.yaml' 
  /user/signin:
    $ref: './docs/user/signIn.yaml' 
  /user/profile:
    $ref: './docs/user/profile.yaml'
  /user/profile/{id}:
    $ref: './docs/user/profileId.yaml'

  /schedule:
    $ref: './docs/schedule/schedule.yaml'
  /schedule/{idx}:
    $ref: './docs/schedule/scheduleIdx.yaml'
  /schedule/name/{idx}:
    $ref: './docs/schedule/scheduleName.yaml'
  /schedule/main/{idx}:
    $ref: './docs/schedule/scheduleMain.yaml'
  /schedule/list:
    $ref: './docs/schedule/scheduleList.yaml'
  /schedule/personal:
    $ref: './docs/schedule/schedulePersonal.yaml'
  /schedule/personal/{idx}:
    $ref: './docs/schedule/schedulePersonalIdx.yaml'
  /schedule/school:
    $ref: './docs/schedule/scheduleSchool.yaml'
  /schedule/school/{idx}:
    $ref: './docs/schedule/scheduleSchoolIdx.yaml'

  /chat:
    $ref: './docs/chat/chat.yaml'

  /notice:
    $ref: './docs/notice/notice.yaml'
  /notice/subject/{idx}:
    $ref: './docs/notice/noticeSubject.yaml'
  /notice/{idx}:
    $ref: './docs/notice/noticeIdx.yaml'

  /cart:
    $ref: './docs/cart/cart.yaml'
  /cart/{idx}:
    $ref: './docs/cart/cartIdx.yaml'

  /subject:
    $ref: './docs/subject/subject.yaml'
  /subject/recommend:
    $ref: './docs/subject/subjectRecommend.yaml'
  /subject/search:
    $ref: './docs/subject/subjectSearch.yaml'
  /subject/course:
      $ref: './docs/subject/subjectCourse.yaml'