openapi: 3.0.0

servers:
  - description: Local test server
    url: http://127.0.0.1:3000
  - description: AWS EC2
    url: http://52.78.27.117:3000

info:
  version: '1.0.0'
  title: 'U-link'
  description: 'University-link'
  contact:
    email: deadlock@kakao.com

tags:
  - name: User
    description: Access User data
  - name: Schedule
    description: Access Schedule data
  - name : Chatting
    description: Access Chatting data
  - name : Notice
    description: Access Notice data
  - name : Social
    description: Access Social data
  - name : Cart
    description: Access Cart data
  - name : Subject
    description: Access Subject data

paths:
  /user/signup:
    $ref: './docs/user/signUp.yaml' 
  /user/signin:
    $ref: './docs/user/signIn.yaml' 
  /user/profile:
    $ref: './docs/user/profile.yaml'
  /user/profile/{id}:
    $ref: './docs/user/profileId.yaml'

  /schedule:
    $ref: './docs/schedule/schedule.yaml'
  /schedule/{idx}:
    $ref: './docs/schedule/scheduleIdx.yaml'
  /schedule/main/{idx}:
    $ref: './docs/schedule/scheduleMain.yaml'
  /schedule/list:
    $ref: './docs/schedule/scheduleList.yaml'
  /schedule/personal:
    $ref: './docs/schedule/schedulePersonal.yaml'
  /schedule/personal/{idx}:
    $ref: './docs/schedule/schedulePersonalIdx.yaml'
  /schedule/school:
    $ref: './docs/schedule/scheduleSchool.yaml'
  /schedule/school/{idx}:
    $ref: './docs/schedule/scheduleSchoolIdx.yaml'

  /chat:
    $ref: './docs/chat/chat.yaml'

  /notice:
    $ref: './docs/notice/notice.yaml'
  /notice/subject/{idx}:
    $ref: './docs/notice/noticeSubject.yaml'
  /notice/{idx}:
    $ref: './docs/notice/noticeIdx.yaml'

  /cart:
    $ref: './docs/cart/cart.yaml'
  /cart/{idx}:
    $ref: './docs/cart/cartIdx.yaml'

  /subject:
    $ref: './docs/subject/subject.yaml'
  /subject/recommend:
    $ref: './docs/subject/subjectRecommend.yaml'
  /subject/search:
    $ref: './docs/subject/subjectSearch.yaml'

components:
  schemas:
    Token:
      required:
        - accessToken
      properties:
        accessToken:
          type: string
          example: eyJhbGkpXVCJ9.eyJ1c2VySWR4Ijoob29sIjoi6rCA7LKc64yA7Z.WZ6rWQIiwiaWF0IjoxNTkzNjcyMTI5LC
        
    UserIdIdx:
      required:
        - userId
        - userIdx
      properties:
        userId:
          type: string
          example: bappe0925
        userIdx:
          type: int
          example: 12

    Fail:
      required:
        - status
        - success
        - message
      properties:
        status:
          type: int
          example: status code number (400~)
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Fail message
      type: object
    UserSignUp:
      required:
        - id
        - name
        - password
        - email
        - school
      properties:
        id:
          type: string
          example: bappe0925
        name:
          type: string
          example: 김보배
        password:
          type: string
          example: passwordword
        email:
          type: string
          example: bappe0925@email.com
        school:
          type: string
          example: 가천대학교
      type: object
    UserSignIn:
      required:
        - id
        - password
      properties:
        id:
          type: string
          example: bappe0925
        password:
          type: string
          example: passwordword
      type: object
    CreatePersonalTimeTable:
      required:
        - name
        - startTime
        - endTime
        - day
        - content
        - color
        - scheduleIdx
      properties:
        name:
          type: string
          example: 자습
        startTime:
          type: string
          example: "18:00"
        endTime:
          type: string
          example: "19:00"
        day:
          type: string
          example: fri
        content: 
          type: string
          example: 독서실
        color:
          type: string
          example: "2"
        scheduleIdx:
          type: string
          example: "1"
      type: object
    CreateSchoolTimeTable:
      required:
        - subjectIdx
        - color
        - scheduleIdx
      properties:
        subjectIdx:
          type: string
          example: "5"
        color:
          type: string
          example: "9"
        scheduleIdx:
          type: string
          example: "1"
      type: object
    UpdateMainTimeTableName:
      required:
        - name
      properties:
        name:
          type: string
          example: "이번에는 1등하자!"
      type: object
    UpdateSchedulePersonal:
      required:
        - name
        - content
        - startTime
        - endTime
        - day
      properties:
        name:
          type: string
          example: "알바"
        content:
          type: string
          example: "카페알바"
        startTime:
          type: string
          example: "20:00"
        endTime:
          type: string
          example: "22:00"
        day:
          type: string
          example: "sat"
      type: object
    CreateCart:
        required:
          - semester
        properties:
          semester:
            type: string
            example: "2020-1"
        type: object
    DeleteCart:
        required:
          - semester
        properties:
          semester:
            type: string
            example: "2020-1"
        type: object        
    CreateNotice:
        required:
          - category
          - date
          - startTime
          - endTime
          - title
          - content
        properties:
          category:
            type: string
            example: "수업"
          date:
            type: string
            example: "2020-12-17"
          startTime:
            type: string
            example: "-1"
          endTime:
            type: string
            example: "-1"
          title:
            type: string
            example: "폐강"
          content:
            type: string
            example: "수업없어짐"
        type: object
    UpdateSpecificNotice:
        required:
          - category
          - date
          - startTime
          - endTime
          - title
          - content
        properties:
          category:
            type: string
            example: "과제"
          date:
            type: string
            example: "2020-07-10"
          startTime:
            type: string
            example: "-1"
          endTime:
            type: string
            example: "12:00"
          title:
            type: string
            example: "논문 작성"
          content:
            type: string
            example: "전자기학이 뭔지 모름;;ㅎㅎ"
        type: object
    
